site_name: libhal
repo_url: https://github.com/libhal/libhal/
repo_name: libhal

theme:
  name: 'material'
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - content.tabs.link
    - toc.integrate
  highlightjs: true
  hljs_style:
    - monokai
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - 'assets/extra.css'

docs_dir: mkdocs

markdown_extensions:
  - admonition
  - pymdownx.mark # highlighting
  - pymdownx.superfences # nest code
  - codehilite # code syntax coding
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink:

nav:
  - ğŸ¡ Home: 'index.md'
  - ğŸ« Tutorials:
    - 'tutorials/setup.md'
    - 'tutorials/glossary.md'
    - 'tutorials/getting_started.md'
    - 'tutorials/configuration.md'
    - 'tutorials/finding_drivers.md'
  - 'design/philosophy.md'
  - 'design/organization.md'
  - 'design/architecture.md'
  - 'design/style.md'
  - 'design/blocks.md'
  - ğŸ”Œ Interfaces:
    - âŒ adc: 'design/adc.md'
    - âœ… dac: 'design/dac.md'
    - âŒ pwm: 'design/pwm.md'

    - âŒ can: 'design/can.md'
    - âŒ spi: 'design/spi.md'
    - âŒ i2c: 'design/i2c.md'
    - âŒ serial: 'design/serial.md'

    - âŒ input_pin: 'design/input_pin.md'
    - âŒ output_pin: 'design/output_pin.md'
    - âŒ interrupt_pin: 'design/interrupt_pin.md'

    - âŒ timer: 'design/timer.md'
    - âŒ steady_clock: 'design/steady_clock.md'

    - âŒ motor: 'design/motor.md'
    - âŒ servo: 'design/servo.md'

    - âŒ socket: 'design/socket.md'
  - ğŸ§ About: 'about.md'
