site_name: libhal
repo_url: https://github.com/libhal/libhal/
repo_name: libhal

theme:
  name: 'material'
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - content.tabs.link
    - toc.integrate
  highlightjs: true
  hljs_style:
    - monokai
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - 'assets/extra.css'

docs_dir: mkdocs

markdown_extensions:
  - admonition
  - pymdownx.mark # highlighting
  - pymdownx.superfences # nest code
  - codehilite # code syntax coding
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink:

nav:
  - ğŸ¡ Home: 'index.md'
  - 'setup.md'
  - 'glossary.md'
  - 'getting_started.md'
  - 'tutorial.md'
  - 'configuration.md'
  - 'finding_drivers.md'
  - 'philosophy.md'
  - 'organization.md'
  - 'architecture.md'
  - 'style.md'
  - 'blocks.md'
  - ğŸ”Œ Interfaces:
    - âŒ adc: 'interfaces/adc.md'
    - âœ… dac: 'interfaces/dac.md'
    - âŒ pwm: 'interfaces/pwm.md'

    - âŒ can: 'interfaces/can.md'
    - âŒ spi: 'interfaces/spi.md'
    - âŒ i2c: 'interfaces/i2c.md'
    - âŒ serial: 'interfaces/serial.md'

    - âŒ input_pin: 'interfaces/input_pin.md'
    - âŒ output_pin: 'interfaces/output_pin.md'
    - âŒ interrupt_pin: 'interfaces/interrupt_pin.md'

    - âŒ timer: 'interfaces/timer.md'
    - âŒ steady_clock: 'interfaces/steady_clock.md'

    - âŒ motor: 'interfaces/motor.md'
    - âŒ servo: 'interfaces/servo.md'

    - âŒ socket: 'interfaces/socket.md'
  - ğŸ§ About: 'about.md'
