# Project Information
site_name: libhal
repo_url: https://github.com/libhal/libhal/
repo_name: libhal
# Configuration
theme:
  name: 'material'
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - content.tabs.link
    - toc.integrate
  highlightjs: true
  hljs_style:
    - monokai
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_css:
  - 'assets/extra.css'

docs_dir: mkdocs

markdown_extensions:
  - admonition
  - pymdownx.mark # highlighting
  - pymdownx.superfences # nest code
  - codehilite # code syntax coding
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - toc:
      permalink:


# Navigation
nav:
  - ğŸ¡ Home: 'index.md'
  - ğŸ« Tutorials:
    - 'tutorials/installation.md'
    - 'tutorials/glossary.md'
    - 'tutorials/getting_started.md'
    - 'tutorials/configuration.md'
    - 'tutorials/finding_drivers.md'
  - ğŸ“– Design Documents:
    - âœ¨ Introduction: 'design/intro.md'
    - ğŸ“œ Philosophy: 'design/philosophy.md'
    - ğŸ—ï¸ Architecture Choices: 'design/architecture.md'
    - ğŸ¨ Style: 'design/style.md'
    - ğŸ§± Building Blocks:
      - timeout: 'design/timeout.md'
      - units: 'design/units.md'
    - ğŸ”Œ Interfaces:
      - adc: 'design/adc.md'
      - can: 'design/can.md'
      - dac: 'design/dac.md'
      - error: 'design/error.md'
      - i2c: 'design/i2c.md'
      - input pin: 'design/input_pin.md'
      - interrupt pin: 'design/interrupt_pin.md'
      - motor: 'design/motor.md'
      - output pin: 'design/output_pin.md'
      - pwm: 'design/pwm.md'
      - serial: 'design/serial.md'
      - servo: 'design/servo.md'
      - socket: 'design/socket.md'
      - spi: 'design/spi.md'
      - steady clock: 'design/steady_clock.md'
      - timer: 'design/timer.md'
  - ğŸ§ About: 'about.md'
